title: Steven Mendoza # your name (or website title) here
logo: "/images/AvatarMaker.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About this site 
  <br><br>
  This website was created by me to showcase my work from my Web Design class 
  <br><br>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
